"""Generators for the synthetic CASTEP fixtures under tests/data/castep_toy.

Every fixture is deterministic text with closed-form physics, so the CASTEP
reader tests anchor to analytic expectations rather than snapshots:

* ``DOS/toy.bands`` encodes parabolic-band densities of states as weighted
  eigenvalue deltas, so the DOS effective-mass fit must recover the chosen
  electron and hole masses.
* ``BAND/toy.bands`` + ``BAND/toy.cell`` hold four cosine bands with a
  1.5 eV direct gap at Gamma along a Gamma-X-M path.
* ``OPT/toy_epsilon.dat`` is a Lorentz oscillator in OptaDOS polycrystalline
  format with eps(0) = 6 exactly.
* ``OPT_TENSOR/toy_epsilon.dat`` is a constant diagonal dielectric tensor in
  OptaDOS ``optics_geom: tensor`` format, lossless by construction.

The committed files are regenerated byte-identically by these functions -
tests assert that, the same provenance discipline the VASP ``absorption.dat``
fixtures follow - so all floats are written with fixed-width formats and the
``__main__`` guard rewrites the whole tree in place.

Format conventions match sumo's strict ``.bands`` reader: a nine-line header,
lattice vectors in Bohr, Fermi energy and eigenvalues in Hartree. Each band
must sit entirely on one side of the header Fermi energy, or sumo's metal
detection disables the valence-band-maximum referencing the DOS tests rely
on; the far-lying "sentinel" eigenvalues below keep that true, and are spread
over an energy range so no single histogram bin dwarfs the physical DOS.
"""

import math
from pathlib import Path

import scipy.constants as sc
from scipy.constants import physical_constants as pc

# Exactly 2 * sumo.io.castep._ry_to_ev, so eV -> Ha -> eV round-trips through
# sumo's reader at float precision.
HA_EV = 27.211386018
# sumo.io.castep._bohr_to_angstrom, the constant sumo applies to .bands lattices.
BOHR_ANG = 0.5291772

HBAR = sc.hbar  # J s
M_E = pc["atomic unit of mass"][0]  # kg
EV = sc.e  # J per eV

# --- shared toy-crystal geometry -------------------------------------------

A_ANG = 5.0  # simple-cubic lattice parameter (Angstrom)
VOLUME_M3 = (A_ANG * 1e-10) ** 3  # 1.25e-28 m^3

# --- DOS fixture parameters ------------------------------------------------

DOS_GAP_EV = 1.5
DOS_M_ELECTRON = 0.30  # target DOS effective masses (units of m_e)
DOS_M_HOLE = 1.20
DOS_WINDOW_EV = 0.3  # energy range of each parabolic ladder
DOS_STEP_EV = 2e-4  # ladder step, 1/50 of the default 0.01 eV bin width
DOS_N_STEPS = int(round(DOS_WINDOW_EV / DOS_STEP_EV))  # k-points per carrier

# --- band-structure fixture parameters -------------------------------------

BAND_GAP_EV = 1.5
BAND_SEGMENT_POINTS = 21  # per path segment, boundary point duplicated

# --- optics fixture parameters ---------------------------------------------

LORENTZ_S = 5.0  # oscillator strength: eps(0) = 1 + S = 6
LORENTZ_E0_EV = 3.0  # resonance energy
LORENTZ_GAMMA_EV = 0.5  # damping
TENSOR_DIAGONAL = (2.0, 3.0, 4.0)  # constant lossless dielectric tensor


def _cumulative_states(energy_ev: float, mass_rel: float) -> float:
    """Integrated parabolic-band DOS from the band edge, in states per cell.

    Evaluates F(E) = (V / 3 pi^2) (2 m E / hbar^2)^(3/2), the spin-summed
    number of states within ``energy_ev`` of the edge for a 3D parabolic band.

    Parameters
    ----------
    energy_ev : float
        Energy from the band edge in eV.
    mass_rel : float
        Band effective mass in units of the free electron mass.

    Returns
    -------
    float
        Cumulative number of states per unit cell, both spins included.
    """
    e_j = energy_ev * EV
    k_sq = 2.0 * mass_rel * M_E * e_j / HBAR**2
    return VOLUME_M3 / (3.0 * math.pi**2) * k_sq**1.5


def _bands_header(n_kpoints: int, n_electrons: float, n_bands: int, e_fermi_ev: float) -> str:
    """Format the nine-line .bands header sumo's reader parses strictly.

    Parameters
    ----------
    n_kpoints : int
        Number of k-point entries that follow.
    n_electrons : float
        Electron count declared in the header.
    n_bands : int
        Eigenvalues per k-point.
    e_fermi_ev : float
        Fermi energy in eV; written in Hartree as the format requires.

    Returns
    -------
    str
        The header text, lattice rows included, ending with a newline.
    """
    a_bohr = A_ANG / BOHR_ANG
    lines = [
        f"Number of k-points {n_kpoints:9d}",
        "Number of spin components         1",
        f"Number of electrons {n_electrons:11.2f}",
        f"Number of eigenvalues {n_bands:9d}",
        f"Fermi energy (in atomic units) {e_fermi_ev / HA_EV: .10e}",
        "Unit cell vectors",
        f" {a_bohr:15.10f} {0.0:15.10f} {0.0:15.10f}",
        f" {0.0:15.10f} {a_bohr:15.10f} {0.0:15.10f}",
        f" {0.0:15.10f} {0.0:15.10f} {a_bohr:15.10f}",
    ]
    return "\n".join(lines) + "\n"


def dos_bands_text() -> str:
    """Build the DOS fixture: parabolic densities as weighted eigenvalue deltas.

    Each k-point carries one physical eigenvalue on a fine energy ladder and
    the k-point weight that makes any histogram of the ladder reproduce the
    parabolic DOS integral over each bin. The first half of the k-points
    paints the hole ladder below the valence band maximum at 0 eV with mass
    ``DOS_M_HOLE``; the second half paints the electron ladder above the
    conduction band minimum at ``DOS_GAP_EV`` with mass ``DOS_M_ELECTRON``.
    Weights are halved because solphin's loader doubles single-spin
    histograms for spin degeneracy.

    The other band at each k-point is a sentinel far outside every fitting
    window, spread over [4, 6] eV (holes) and [-6, -4] eV (electrons) so its
    histogram stays comparable to the physical DOS - pymatgen's band-edge
    search uses a tolerance relative to the largest density, which a single
    sentinel spike would distort.

    Returns
    -------
    str
        Complete .bands file contents.
    """
    n_kpoints = 2 * DOS_N_STEPS
    text = [_bands_header(n_kpoints, 2.0, 2, DOS_GAP_EV / 2.0)]

    def kpoint_entry(index: int, weight: float, band1_ev: float, band2_ev: float) -> str:
        """Format one k-point entry with its two eigenvalue lines.

        Parameters
        ----------
        index : int
            One-based k-point index.
        weight : float
            K-point weight carried by both eigenvalues.
        band1_ev : float
            First eigenvalue in eV.
        band2_ev : float
            Second eigenvalue in eV.

        Returns
        -------
        str
            The formatted entry, ending with a newline.
        """
        return (
            f"K-point {index:5d} {index / n_kpoints:12.8f} {0.0:12.8f} {0.0:12.8f}"
            f" {weight:.12e}\n"
            "Spin component 1\n"
            f"{band1_ev / HA_EV: .14e}\n"
            f"{band2_ev / HA_EV: .14e}\n"
        )

    for j in range(DOS_N_STEPS):
        low, high = j * DOS_STEP_EV, (j + 1) * DOS_STEP_EV
        weight = (
            _cumulative_states(high, DOS_M_HOLE) - _cumulative_states(low, DOS_M_HOLE)
        ) / 2.0
        valence = -(j + 0.5) * DOS_STEP_EV
        sentinel = 4.0 + 2.0 * j / DOS_N_STEPS
        text.append(kpoint_entry(j + 1, weight, valence, sentinel))

    for j in range(DOS_N_STEPS):
        low, high = j * DOS_STEP_EV, (j + 1) * DOS_STEP_EV
        weight = (
            _cumulative_states(high, DOS_M_ELECTRON)
            - _cumulative_states(low, DOS_M_ELECTRON)
        ) / 2.0
        conduction = DOS_GAP_EV + (j + 0.5) * DOS_STEP_EV
        sentinel = -(4.0 + 2.0 * j / DOS_N_STEPS)
        text.append(kpoint_entry(DOS_N_STEPS + j + 1, weight, sentinel, conduction))

    return "".join(text)


def _band_path() -> list[tuple[float, float, float]]:
    """Return the Gamma-X-M path with the segment boundary duplicated.

    Returns
    -------
    list of tuple of float
        Fractional k-point coordinates, 2 * BAND_SEGMENT_POINTS entries.
    """
    n = BAND_SEGMENT_POINTS
    gamma_x = [(0.5 * i / (n - 1), 0.0, 0.0) for i in range(n)]
    x_m = [(0.5, 0.5 * i / (n - 1), 0.0) for i in range(n)]
    return gamma_x + x_m


def _band_energies(kpt: tuple[float, float, float]) -> list[float]:
    """Evaluate the four cosine bands at one k-point.

    The valence pair peaks at exactly 0 eV at Gamma and the conduction pair
    dips to exactly ``BAND_GAP_EV`` there, so the gap is direct at Gamma by
    construction.

    Parameters
    ----------
    kpt : tuple of float
        Fractional k-point coordinates.

    Returns
    -------
    list of float
        The four band energies in eV, valence first.
    """
    dispersion = (2.0 - math.cos(2 * math.pi * kpt[0]) - math.cos(2 * math.pi * kpt[1])) / 2.0
    return [
        -1.0 - dispersion,
        0.0 - dispersion,
        BAND_GAP_EV + dispersion,
        BAND_GAP_EV + 1.0 + dispersion,
    ]


def band_bands_text() -> str:
    """Build the band-structure .bands fixture along the Gamma-X-M path.

    Returns
    -------
    str
        Complete .bands file contents.
    """
    path = _band_path()
    text = [_bands_header(len(path), 4.0, 4, BAND_GAP_EV / 2.0)]

    for index, kpt in enumerate(path, start=1):
        text.append(
            f"K-point {index:5d} {kpt[0]:12.8f} {kpt[1]:12.8f} {kpt[2]:12.8f}"
            f" {1.0 / len(path):.12e}\n"
            "Spin component 1\n"
        )
        for energy in _band_energies(kpt):
            text.append(f"{energy / HA_EV: .14e}\n")

    return "".join(text)


def band_cell_text() -> str:
    """Build the .cell fixture naming the high-symmetry points of the path.

    Only the labelled rows carry a trailing comment: sumo's label reader
    treats any row with more than three tokens as labelled, and maps ``G``
    to the Gamma symbol.

    Returns
    -------
    str
        Complete .cell file contents.
    """
    a = A_ANG
    lines = [
        "%block lattice_cart",
        "ang",
        f"{a:.6f} 0.000000 0.000000",
        f"0.000000 {a:.6f} 0.000000",
        f"0.000000 0.000000 {a:.6f}",
        "%endblock lattice_cart",
        "",
        "%block positions_frac",
        "Si 0.0 0.0 0.0",
        "%endblock positions_frac",
        "",
        "%block spectral_kpoint_list",
    ]

    labels = {0: "G", BAND_SEGMENT_POINTS - 1: "X", 2 * BAND_SEGMENT_POINTS - 1: "M"}
    for index, kpt in enumerate(_band_path()):
        row = f"{kpt[0]:12.8f} {kpt[1]:12.8f} {kpt[2]:12.8f}"
        if index in labels:
            row += f" ! {labels[index]}"
        lines.append(row)

    lines.append("%endblock spectral_kpoint_list")
    return "\n".join(lines) + "\n"


def lorentz_epsilon(energy_ev: float) -> complex:
    """Evaluate the Lorentz-oscillator dielectric function of the OPT fixture.

    Parameters
    ----------
    energy_ev : float
        Photon energy in eV.

    Returns
    -------
    complex
        The model dielectric function at that energy.
    """
    numerator = LORENTZ_S * LORENTZ_E0_EV**2
    denominator = complex(
        LORENTZ_E0_EV**2 - energy_ev**2, -LORENTZ_GAMMA_EV * energy_ev
    )
    return 1.0 + numerator / denominator


def epsilon_poly_text() -> str:
    """Build the polycrystalline OptaDOS epsilon fixture from the Lorentz model.

    Returns
    -------
    str
        Complete ``toy_epsilon.dat`` contents: one data block of
        energy / Re(eps) / Im(eps) columns under OptaDOS-style comments.
    """
    lines = [
        "# OptaDOS output - synthetic test fixture (Lorentz oscillator)",
        "# Dielectric function (polycrystalline)",
        "# Energy (eV)   Real          Imag",
    ]
    for i in range(501):
        energy = 0.02 * i
        eps = lorentz_epsilon(energy)
        lines.append(f"{energy:10.4f} {eps.real: .12e} {eps.imag: .12e}")
    return "\n".join(lines) + "\n"


def epsilon_tensor_text() -> str:
    """Build the tensor-geometry OptaDOS epsilon fixture, lossless by design.

    Six blocks in OptaDOS component order (xx, yy, zz, xy, xz, yz), each
    preceded by a ``# Component: i j`` comment, with a constant real diagonal
    of ``TENSOR_DIAGONAL`` and zero off-diagonal and imaginary parts.

    Returns
    -------
    str
        Complete ``toy_epsilon.dat`` contents.
    """
    lines = [
        "# OptaDOS output - synthetic test fixture (constant tensor)",
        "# Dielectric function (optics_geom: tensor)",
    ]
    components = [(1, 1), (2, 2), (3, 3), (1, 2), (1, 3), (2, 3)]
    for i, j in components:
        value = TENSOR_DIAGONAL[i - 1] if i == j else 0.0
        lines.append(f"# Component: {i} {j}")
        for step in range(101):
            energy = 0.05 * step
            lines.append(f"{energy:10.4f} {value: .12e} {0.0: .12e}")
    return "\n".join(lines) + "\n"


def generate_all(root: Path) -> None:
    """Write every fixture file into the castep_toy tree.

    Parameters
    ----------
    root : Path
        Directory that becomes ``castep_toy``; subdirectories are created.
    """
    targets = {
        root / "DOS" / "toy.bands": dos_bands_text,
        root / "BAND" / "toy.bands": band_bands_text,
        root / "BAND" / "toy.cell": band_cell_text,
        root / "OPT" / "toy_epsilon.dat": epsilon_poly_text,
        root / "OPT_TENSOR" / "toy_epsilon.dat": epsilon_tensor_text,
    }
    for path, build in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(build(), encoding="utf-8")


if __name__ == "__main__":
    generate_all(Path(__file__).resolve().parent / "data" / "castep_toy")
